services:
  - type: web
    name: style-transfer-frontend
    env: static
    buildCommand: echo "Static site build"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
