services:
  - type: web
    name: style-transfer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: style-transfer-disk
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1
